import {useState} from 'react'
import {useQuery} from '@tanstack/react-query'
import {Link,Navigate,useOutletContext} from 'react-router-dom'
import {Radar,ExternalLink,Link2} from 'lucide-react'
import {request,errorText,refresh} from '../../api/client'
import type {Me,Product,Topic} from '../../types'
import {categories} from '../../types'
import {Modal} from '../ui/Modal'
export function TopicsPage(){
 const me=useOutletContext<Me>(),[category,setCategory]=useState(''),[product,setProduct]=useState(''),[open,setOpen]=useState(false),[url,setURL]=useState(''),[importID,setImportID]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const products=useQuery({queryKey:['products'],queryFn:()=>request<{items:Product[]}>('/products')})
 const topics=useQuery({queryKey:['topics',category,product],queryFn:({signal})=>request<{items:Topic[];collector_configured:boolean;matching_error?:string}>('/topics?'+new URLSearchParams({category,product_id:product}),'GET',undefined,signal)})
 const importing=useQuery({queryKey:['import',importID],enabled:!!importID,queryFn:()=>request<{status:string;topic_id?:string;error?:string}>('/topic-imports/'+importID),refetchInterval:query=>query.state.data?.status==='succeeded'||query.state.data?.status==='failed'?false:3000})
 if(me.user.role==='admin')return <Navigate to="/admin" replace/>
 return <><div className="page-heading"><div><p className="eyebrow">A LITTLE INSPIRATION</p><h1>今日选题</h1><p className="muted">从行业账号内容中发现创作灵感，找到适合你的商品表达。</p></div><button onClick={()=>setOpen(true)}><Link2 size={18}/>导入抖音链接</button></div><div className="toolbar"><select aria-label="选题类目" value={category} onChange={e=>{setCategory(e.target.value);setProduct('')}}><option value="">全部行业</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select aria-label="匹配商品" value={product} onChange={e=>setProduct(e.target.value)}><option value="">选择商品查看匹配建议</option>{products.data?.items.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></div><p className="notice">来源：管理员监控的行业账号与用户导入。热度依据公开互动、增长和时效，不包含完播或成交数据。</p>
 {topics.isPending?<div className="empty">正在加载灵感…</div>:topics.error?<div className="empty error">{errorText(topics.error)}<button onClick={()=>void topics.refetch()}>重试</button></div>:!topics.data?.items.length?<div className="empty"><Radar size={40}/><h2>{topics.data?.collector_configured?'还没有可用选题':'选题服务尚未配置'}</h2><p className="muted">可以先从商品展示开始，热点灵感随时再加。</p><Link className="primary" to="/products">生成商品素材</Link></div>:<div className="topic-grid">{topics.data.items.map((t,i)=><article className="panel topic-card" key={t.id}><div className="row"><span className="rank">{String(i+1).padStart(2,'0')}</span><span className="badge">{t.status_tag}</span></div><h2>{t.title}</h2><p className="muted">{t.author} · {t.category}</p><p>{t.angle_summary||t.description}</p><div className="topic-metrics"><span>加权互动<strong>{t.weighted_interaction===null?'未知':Math.round(t.weighted_interaction).toLocaleString()}</strong></span><span>每小时增长<strong>{t.hourly_growth===null?'未知':Math.round(t.hourly_growth).toLocaleString()}</strong></span>{t.match_score!==undefined&&<span>商品适配<strong>{t.match_score}%</strong></span>}</div>{t.match_reason&&<p className="muted">{t.match_reason}</p>}<div className="actions"><a href={t.original_url} target="_blank" rel="noreferrer"><ExternalLink size={16}/>查看来源</a>{product&&<Link className="primary" to={'/create?product='+product+'&topic='+t.id}>用这个灵感创作</Link>}</div><small className="muted">更新于 {new Date(t.crawled_at).toLocaleString()}</small></article>)}</div>}
 {topics.data?.matching_error&&<p className="muted">{topics.data.matching_error}</p>}
 <Modal isOpen={open} title="导入选题" onClose={()=>setOpen(false)}><p className="muted">粘贴抖音作品链接，解析完成后可用于你的商品创作。</p><label>作品链接<input type="url" value={url} onChange={e=>setURL(e.target.value)} placeholder="https://v.douyin.com/…"/></label><button className="primary" disabled={busy||!url} onClick={async()=>{setBusy(true);setError('');try{const result=await request<{id:string}>('/topic-imports','POST',{url});setImportID(result.id)}catch(e){setError(errorText(e))}finally{setBusy(false)}}}>解析链接</button>{error&&<p className="error">{error}</p>}{importID&&<p>{importing.data?.status==='succeeded'?'已导入':importing.data?.status==='failed'?importing.data.error:'正在云端解析，可关闭窗口稍后查看'}</p>}{importing.data?.status==='succeeded'&&<button onClick={()=>{setOpen(false);refresh('topics')}}>查看选题</button>}</Modal></>
}
