import {useEffect,useState} from 'react'
import {useQuery} from '@tanstack/react-query'
import {Link,useParams} from 'react-router-dom'
import {ArrowLeft,Download} from 'lucide-react'
import {request,refresh,errorText,exportGeneration} from '../../api/client'
import type {Generation,CopyData,Quote} from '../../types'
import {Badge} from '../ui/Badge'
import {Photo} from '../ui/Photo'
import {ImageCompare} from '../ui/ImageCompare'
import {Modal} from '../ui/Modal'
import {useToast} from '../ui/Toast'
export function TaskDetailModal(){
 const {id}=useParams(),toast=useToast(),[draft,setDraft]=useState<CopyData>(),[dirty,setDirty]=useState(false),[baseVersion,setBaseVersion]=useState(0),[busy,setBusy]=useState(false),[compare,setCompare]=useState(''),[retry,setRetry]=useState<Quote>()
 const task=useQuery({queryKey:['generation',id],queryFn:()=>request<Generation>('/generations/'+id),refetchInterval:3000})
 useEffect(()=>{if(!dirty&&task.data){setDraft(task.data.copy_data);setBaseVersion(task.data.copy_version)}},[task.data,dirty])
 function change(next:CopyData){setDraft(next);setDirty(true)}
 async function save(){if(!draft||!task.data)return;await request('/generations/'+id+'/copy','POST',{copy_data:draft,expected_version:baseVersion});setDirty(false);refresh('generation');toast.success('文案已保存，正在更新图片')}
 async function download(){setBusy(true);try{if(dirty)await save();for(let n=0;n<60;n++){const current=await request<Generation>('/generations/'+id);if(!current.render_pending){await exportGeneration(id!);return}await new Promise(resolve=>setTimeout(resolve,1000))}throw new Error('图片仍在更新，请稍后下载')}catch(e){toast.error(errorText(e))}finally{setBusy(false)}}
 if(!task.data)return <div className="empty">{task.error?errorText(task.error):'正在加载作品…'}</div>
 const g=task.data,running=g.status==='running'||g.status==='queued'
 return <><Link className="back-link" to="/creations"><ArrowLeft size={16}/>我的作品</Link><div className="page-heading"><div><p className="eyebrow">CONTENT DELIVERY</p><h1>{g.product_name}</h1><p className="muted">{g.preset==='product_showcase'?'商品展示':'抖音带货'} · 已结算 {g.settled_credits} 点 · 已退还 {g.released_credits} 点</p></div><div className="actions"><Badge status={g.status}/><button className="primary" disabled={busy||running||g.render_pending} onClick={()=>void download()}><Download size={18}/>{busy?'准备下载…':'下载素材包'}</button></div></div>
 {g.status==='needs_review'&&<p className="notice">部分接口结果待管理员核实，系统不会自动重复调用。已完成素材可下载。</p>}{g.status==='partial'&&<p className="notice">部分素材未完成，成功单项已保留，明确失败单项已退还额度。</p>}{g.status==='queued'&&<button onClick={async()=>{try{await request('/generations/'+id+'/cancel','POST');refresh('generation','me')}catch(e){toast.error(errorText(e))}}}>取消等待中的任务</button>}
 <div className="detail-layout"><section><div className="asset-grid">{g.artifacts.filter(it=>it.type!=='copywriting').map(it=>{const current=it.versions.find(v=>v.is_selected);return <article className="panel" key={it.id}><div className="row"><h2>{it.name}</h2><Badge status={it.status}/></div><div className="asset-photo"><Photo src={current?.url} alt={it.name} contain/></div>{it.error_message&&<p className="error">{it.error_message}</p>}{current&&<button onClick={()=>setCompare(current.url)}>与原图对比 / 放大</button>}{it.versions.length>1&&<label>导出使用的图片版本<select value={current?.id||''} onChange={async e=>{try{await request('/generations/'+id+'/selection','POST',{asset_id:e.target.value});refresh('generation')}catch(e){toast.error(errorText(e))}}}>{it.versions.map((v,i)=><option key={v.id} value={v.id}>版本 {it.versions.length-i} · {v.copy_version?'文案 '+v.copy_version:'模型图片'}</option>)}</select></label>}{it.provider_type==='image'&&!running&&it.status!=='needs_review'&&<button onClick={async()=>{try{setRetry(await request<Quote>('/generations/'+id+'/retry','POST',{item_type:it.type}))}catch(e){toast.error(errorText(e))}}}>重新生成此图</button>}</article>})}</div></section>
 <aside className="panel copy-editor"><h2>商品文案</h2><p className="muted">手动调整免费，保存后同步更新排版图片。</p>{draft&&<>{draft.titles.map((title,i)=><label key={i}>标题 {i+1}<textarea disabled={running} value={title} onChange={e=>change({...draft,titles:draft.titles.map((s,n)=>n===i?e.target.value:s)})}/></label>)}<label>描述<textarea rows={5} disabled={running} value={draft.description} onChange={e=>change({...draft,description:e.target.value})}/></label><label>卖点（每行一条）<textarea disabled={running} value={draft.selling_points.join('\n')} onChange={e=>change({...draft,selling_points:e.target.value.split('\n')})}/></label>{draft.script&&<label>口播脚本<textarea rows={6} disabled={running} value={draft.script.text} onChange={e=>change({...draft,script:{text:e.target.value,estimated_seconds:30}})}/></label>}{draft.caption&&<label>发布文案<textarea disabled={running} value={draft.caption.text} onChange={e=>change({...draft,caption:{text:e.target.value,tags:draft.caption?.tags||[]}})}/></label>}<div className="actions"><button className="primary" disabled={busy||running||(!dirty&&!g.artifacts.some(it=>it.provider_type==='template'&&it.status==='failed'))} onClick={async()=>{setBusy(true);try{await save()}catch(e){toast.error(errorText(e))}finally{setBusy(false)}}}>保存并更新图片</button><button onClick={async()=>{try{await navigator.clipboard.writeText([...draft.titles,draft.description,...draft.selling_points,draft.script?.text||'',draft.caption?.text||''].join('\n\n'));toast.success('已复制文案')}catch{toast.error('复制失败，请手动选择文案')}}}>复制</button></div>{dirty&&<p className="muted">有未保存修改 · 下载前将先保存</p>}{g.render_pending&&<p role="status" className="muted">文案已保存 · 图片更新中…</p>}</>}</aside></div>
 <Modal isOpen={!!compare} title="检查商品细节" onClose={()=>setCompare('')}><ImageCompare original={g.product_image_url} generated={compare}/></Modal><Modal isOpen={!!retry} title="确认重新生成" onClose={()=>setRetry(undefined)}>{retry&&<><p>{retry.items[0].name} · {retry.total_credits} 点</p><p className="muted">原图片版本保留，新的图片完成后可选择用于导出。</p><button className="primary" disabled={busy||Date.parse(retry.expires_at)<Date.now()} onClick={async()=>{setBusy(true);try{await request('/generations','POST',{quote_id:retry.quote_id,idempotency_key:retry.idempotency_key});setRetry(undefined);refresh('generation','me')}catch(e){toast.error(errorText(e))}finally{setBusy(false)}}}>确认生成</button></>}</Modal></>
}
