import {useEffect,useRef,useState} from 'react'
import {useQuery} from '@tanstack/react-query'
import {Link,Navigate,useNavigate,useOutletContext,useSearchParams} from 'react-router-dom'
import {ArrowLeft,Sparkles} from 'lucide-react'
import {request,refresh,errorText} from '../../api/client'
import type {Me,Product,Preset,Quote,QuoteItem,Topic} from '../../types'
import {Photo} from '../ui/Photo'
export function GenerationStudio(){
 const me=useOutletContext<Me>(),navigate=useNavigate(),[params,setParams]=useSearchParams()
 const pid=params.get('product')||'',topicID=params.get('topic')||''
 const [preset,setPreset]=useState<Preset>('product_showcase'),[search,setSearch]=useState(''),[quote,setQuote]=useState<Quote>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now()),seq=useRef(0)
 const product=useQuery({queryKey:['product',pid],enabled:!!pid,queryFn:({signal})=>request<Product>('/products/'+pid,'GET',undefined,signal)})
 const choices=useQuery({queryKey:['products',search],queryFn:({signal})=>request<{items:Product[]}>('/products?q='+encodeURIComponent(search),'GET',undefined,signal)})
 const presets=useQuery({queryKey:['presets'],queryFn:()=>request<{presets:{id:Preset;name:string;items:QuoteItem[];total_credits:number}[]}>('/presets')})
 const topics=useQuery({queryKey:['topics',pid],enabled:!!pid,queryFn:({signal})=>request<{items:Topic[]}>('/topics?product_id='+pid,'GET',undefined,signal)})
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[])
 useEffect(()=>{setQuote(undefined);setError('');const current=++seq.current;if(!pid)return;const controller=new AbortController();void request<Quote>('/generations/quote','POST',{product_id:pid,preset,topic_id:topicID},controller.signal).then(q=>{if(current===seq.current)setQuote(q)}).catch(e=>{if(!controller.signal.aborted)setError(errorText(e))});return()=>controller.abort()},[pid,preset,topicID,product.data?.version])
 function changeProduct(id:string){setQuote(undefined);setParams({product:id})}
 const valid=quote&&quote.product_id===pid&&quote.preset===preset&&(quote.topic_id||'')===topicID&&Date.parse(quote.expires_at)>now
 if(me.user.role==='admin')return <Navigate to="/admin" replace/>
 return <><Link className="back-link" to="/products"><ArrowLeft size={16}/>我的商品</Link><div className="page-heading"><div><p className="eyebrow">CREATE SOMETHING NEW</p><h1>生成商品素材</h1><p className="muted">选择商品和内容类型，图片与文案一次准备好。</p></div></div><div className="studio-layout"><div className="studio-steps"><section className="panel"><h2><span className="step">1</span>选择商品</h2>{product.data&&<div className="selected-product"><div><Photo src={product.data.reference_images[0]?.url} alt={product.data.name} contain/></div><article><h3>{product.data.name}</h3><p className="muted">{product.data.category} · 使用当前商品资料</p></article></div>}<label>搜索并选择商品<input placeholder="输入商品名称" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="选择商品" value={pid} onChange={e=>changeProduct(e.target.value)}><option value="">请选择商品</option>{product.data&&!choices.data?.items.some(p=>p.id===pid)&&<option value={pid}>{product.data.name}</option>}{choices.data?.items.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{product.error&&<p className="error">{errorText(product.error)}</p>}</section>
 <section className="panel"><h2><span className="step">2</span>选择内容类型</h2><div className="preset-grid">{presets.data?.presets.map(p=><button className={'preset '+(preset===p.id?'selected':'')} key={p.id} onClick={()=>{setQuote(undefined);setPreset(p.id)}} aria-pressed={preset===p.id}><strong>{p.name}</strong><span>{p.items.map(i=>i.name).join('、')}</span><small>{p.total_credits} 点 / 包</small></button>)}</div>{presets.error&&<p className="error">{errorText(presets.error)}</p>}</section>
 <details className="panel"><summary>添加热点灵感 <span className="muted">可选</span></summary><p className="muted">没有选题也能创作商品展示素材。</p><select aria-label="热点灵感" value={topicID} onChange={e=>{setQuote(undefined);setParams(e.target.value?{product:pid,topic:e.target.value}:{product:pid})}}><option value="">不添加选题</option>{topics.data?.items.map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select>{topics.error&&<p className="muted">热点暂不可用，可直接生成商品展示。</p>}</details></div>
 <aside className="panel quote-panel"><p className="eyebrow">YOUR CONTENT PACKAGE</p><h2>本次生成</h2><div className="delivery-preview"><Sparkles size={32}/><p>让商品成为画面主角</p><span className="muted">真实参考图 · 清晰交付 · 可修改文案</span></div>{quote?<><ul className="quote-items">{quote.items.map(i=><li key={i.item_type}><span>{i.name}</span><span>{i.credits===0?'免费排版':i.credits+' 点'}</span></li>)}</ul><div className="quote-total"><span>合计</span><strong>{quote.total_credits} <small>点</small></strong></div><p className="muted">{valid?'报价剩余 '+Math.max(0,Math.ceil((Date.parse(quote.expires_at)-now)/60000))+' 分钟':'报价已失效，请重新获取'}</p></>:<p className="muted">{pid&&!error?'正在获取本次生成内容…':'先选择一件商品'}</p>}{error&&<p role="alert" className="error">{error}</p>}
 <div className="generate-action"><button className="primary" disabled={!valid||busy} onClick={async()=>{if(!valid||!quote)return;setBusy(true);try{const task=await request<{id:string}>('/generations','POST',{quote_id:quote.quote_id,idempotency_key:quote.idempotency_key});refresh('me','generations');navigate('/creations/'+task.id)}catch(e){setError(errorText(e));setQuote(undefined)}finally{setBusy(false)}}}>{busy?'正在创建任务':'生成素材'}</button></div>{pid&&(!valid||error)&&<button onClick={async()=>{setQuote(undefined);setError('');try{setQuote(await request<Quote>('/generations/quote','POST',{product_id:pid,preset,topic_id:topicID}))}catch(e){setError(errorText(e))}}}>重新获取报价</button>}<p className="muted">手动修改文案与更新排版免费。明确失败的单项会退还预占额度。</p></aside></div></>
}
