import {useState} from 'react'
import type {FormEvent} from 'react'
import {Upload,ArrowLeft,ArrowRight} from 'lucide-react'
import {request,errorText} from '../../api/client'
import type {Product,Reference} from '../../types'
import {categories} from '../../types'
import {Modal} from '../ui/Modal'
import {Photo} from '../ui/Photo'
type Pending={id:string;file:File;status:string;error?:string}
export function ProductModal({product,vision,onClose}:{product:Product|null;vision:boolean;onClose:()=>void}){
 const [id,setID]=useState(product?.id||''),[refs,setRefs]=useState<Reference[]>(product?.reference_images||[]),[files,setFiles]=useState<Pending[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[suggestion,setSuggestion]=useState<Product>()
 const [values,setValues]=useState({name:product?.name||'',category:product?.category||'',brand:product?.brand||'',external_sku:product?.external_sku||'',color:product?.color||'',price:product?.price===null||product?.price===undefined?'':String(product.price),selling_points:product?.selling_points.join('\n')||'',usage_scenarios:product?.usage_scenarios.join('\n')||''})
 function add(selected:FileList|File[]|null){if(!selected)return;const incoming=Array.from(selected);if(refs.length+files.length+incoming.length>6){setError('每件商品最多6张参考图');return}const valid:Pending[]=[];for(const file of incoming){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){setError(file.name+'：仅支持 JPEG、PNG、WebP，且每张最多10 MiB');continue}valid.push({id:crypto.randomUUID(),file,status:'待上传'})}setFiles(prev=>[...prev,...valid])}
 async function upload(pid:string,file:Pending){setFiles(prev=>prev.map(p=>p.id===file.id?{...p,status:'上传中',error:undefined}:p));try{const body=new FormData();body.append('file',file.file);const ref=await request<Reference>('/products/'+pid+'/references','POST',body);setRefs(prev=>[...prev,ref]);setFiles(prev=>prev.filter(p=>p.id!==file.id));return true}catch(e){setFiles(prev=>prev.map(p=>p.id===file.id?{...p,status:'上传失败',error:errorText(e)}:p));return false}}
 async function save(event:FormEvent){event.preventDefault();if(!refs.length&&!files.length){setError('请至少添加一张参考图');return}setBusy(true);setError('');try{const payload={...values,price:values.price===''?null:Number(values.price),selling_points:values.selling_points.split('\n').filter(Boolean),usage_scenarios:values.usage_scenarios.split('\n').filter(Boolean)};const result=await request<Product>('/products'+(id?'/'+id:''),id?'PUT':'POST',payload);setID(result.id);let success=true;for(const file of files)if(!await upload(result.id,file))success=false;if(success)onClose();else setError('资料已保存，请重试上传失败的图片')}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function reorder(from:number,to:number){if(to<0||to>=refs.length)return;const next=[...refs];const [item]=next.splice(from,1);next.splice(to,0,item);try{await request('/products/'+id+'/references','PUT',{ids:next.map(r=>r.id)});setRefs(next)}catch(e){setError(errorText(e))}}
 return <Modal isOpen title={product?'编辑商品':'新增商品'} onClose={()=>{if(!busy)onClose()}}><form onSubmit={save}><div className="form-grid"><label>商品名称 *<input required maxLength={200} value={values.name} onChange={e=>setValues({...values,name:e.target.value})}/></label><label>类目 *<select required value={values.category} onChange={e=>setValues({...values,category:e.target.value})}><option value="">请选择类目</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div>
 <label className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();add(e.dataTransfer.files)}}><Upload size={24}/><strong>选择或拖放商品参考图 *</strong><span>最多6张，每张10 MiB · JPEG / PNG / WebP</span><input aria-label="商品参考图" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{add(e.target.files);e.target.value=''}}/></label>
 <div className="reference-grid">{refs.map((ref,i)=><div key={ref.id}><Photo src={ref.url} alt={ref.file_name} contain/><small>{i===0?'主图':'参考图 '+(i+1)}</small><div className="reference-actions"><button type="button" aria-label="向前移动" onClick={()=>void reorder(i,i-1)} disabled={i===0}><ArrowLeft size={16}/></button><button type="button" aria-label="向后移动" onClick={()=>void reorder(i,i+1)} disabled={i===refs.length-1}><ArrowRight size={16}/></button><button type="button" onClick={async()=>{try{await request('/products/'+id+'/references/'+ref.id,'DELETE');setRefs(refs.filter(r=>r.id!==ref.id))}catch(e){setError(errorText(e))}}}>移除</button></div>{i>0&&<button type="button" onClick={()=>void reorder(i,0)}>设为主图</button>}</div>)}</div>
 {files.map(file=><div className="upload-status" key={file.id}><span>{file.file.name} · {file.status}</span>{file.error&&<span className="error">{file.error}</span>}{id&&file.status==='上传失败'&&<button type="button" onClick={()=>void upload(id,file)}>重试</button>}<button type="button" disabled={file.status==='上传中'} onClick={()=>setFiles(files.filter(f=>f.id!==file.id))}>移除</button></div>)}
 <details><summary>可选资料：品牌、SKU、卖点和使用场景</summary><div className="form-grid">{(['brand','external_sku','color','price'] as const).map((key,i)=><label key={key}>{['品牌','SKU','颜色','价格（元）'][i]}<input type={key==='price'?'number':'text'} min={0} value={values[key]} onChange={e=>setValues({...values,[key]:e.target.value})}/></label>)}</div><label>已确认卖点（每行一条，最多8条）<textarea value={values.selling_points} onChange={e=>setValues({...values,selling_points:e.target.value})}/></label><label>使用场景（每行一条）<textarea value={values.usage_scenarios} onChange={e=>setValues({...values,usage_scenarios:e.target.value})}/></label></details>
 {vision&&id&&refs.length>0&&<button type="button" onClick={async()=>{try{const result=await request<{suggestions:Product}>('/products/'+id+'/analyze','POST');setSuggestion(result.suggestions)}catch(e){setError(errorText(e))}}}>识别商品资料</button>}
 {suggestion&&<div className="notice"><p>请确认识别结果：{suggestion.name} / {suggestion.category} / {suggestion.color}</p><button type="button" onClick={()=>{setValues({...values,name:suggestion.name||values.name,category:categories.includes(suggestion.category)?suggestion.category:values.category,color:suggestion.color||values.color});setSuggestion(undefined)}}>确认采用</button></div>}
 {error&&<p className="error" role="alert">{error}</p>}<div className="actions"><button type="button" disabled={busy} onClick={onClose}>取消</button><button className="primary" disabled={busy}>{busy?'正在保存与上传…':'保存商品'}</button></div></form></Modal>
}
